### ISSUE TITLE
Empty fieldset when there are no product terms

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-terms-per-product#7]
Noticed while working on EDD site: 

<img width="1118" alt="screen shot 2017-12-03 at 1 16 51 pm" src="https://user-images.githubusercontent.com/2359131/33529933-46058ece-d82c-11e7-9aae-cc9537018489.png">

The bottom box would be holding terms for a specific product. But nothing in the cart has its own terms. The `fieldset` shouldn't display in that case.

**Comment by pippinsplugins** [comment]
@SDavisMedia looks good! Could you please deploy this to WordPress.org when able? I've added you as a committer.

**Comment by SDavisMedia** [comment]
@pippinsplugins Yup!

**Comment by SDavisMedia** [comment]
@pippinsplugins I can update the plugin manually no problem but I'm curious if we use that deploy script in the root? I've never noticed it before. If it's something we use, I wanna learn it. Not finding any information on how to run it, though.
